(() => {
  const categories = {
    "Impreza": [
      "Ochroniarz twierdzi, że jedna owca tańczyła na barze.","DJ oddaje wam mikrofon i każe wybrać hymn stada.","Ktoś zamówił 14 shotów na rachunek stada.","W klubie właśnie pojawił się były jednej z owiec.","Barman proponuje wam drinka o nazwie 'Zły Pomysł'.","Jedna owca zgubiła but i twierdzi, że to część stylizacji.","Stado ma wejść do VIP roomu, ale tylko trzy owce są na liście.","Ktoś wysłał kompromitujące zdjęcie na grupę rodzinną.","Na parkiecie zaczyna się bitwa taneczna z innym stadem.","Wasz stolik przejęła grupa bardzo pewnych siebie alpak.","DJ pyta, kto z was ma przejąć konsoletę.","Jedna owca nagle oświadcza, że zna właściciela klubu.","Ktoś przynosi tort z napisem nie dla tej imprezy.","Do stolika podchodzi osoba, która zna jedną z was z aplikacji randkowej.","Ostatni tramwaj odjechał, a stado ma jeszcze energię.","Ktoś zaczyna rozdawać numery telefonu w imieniu całej grupy.","Macie jedno wolne miejsce w limuzynie.","Ochrona prosi o wskazanie najbardziej odpowiedzialnej osoby.","Jedna owca wraca z tajemniczą koroną i nie chce powiedzieć skąd ją ma.","W barze jest konkurs karaoke z absurdalnie wysoką nagrodą.","Ktoś zamawia szampana, którego cena wygląda jak numer telefonu.","Stado odkrywa fotobudkę z trybem 'bez cenzury'.","Ktoś proponuje przenieść imprezę do mieszkania poznanych pięć minut temu ludzi.","Jedna owca zaczyna negocjować z DJ-em jak prezes na walnym zgromadzeniu.","Na parkiecie pojawia się kamera lokalnej telewizji.","Macie wybrać jedną osobę do konkursu jedzenia ostrej papryki.","Ktoś słyszy, że w sąsiednim lokalu jest znacznie lepsza impreza.","Kelner przynosi rachunek, którego nikt nie pamięta.","Jedna owca zniknęła na 40 minut i wraca z balonem w kształcie flaminga.","Klub zamyka się, ale obsługa proponuje wam jedną ostatnią decyzję."
    ],
    "Randki": [
      "Na wspólnej kolacji pojawia się ktoś, z kim jedna owca kiedyś randkowała.","Aplikacja randkowa pokazuje idealne dopasowanie 30 metrów od was.","Jedna owca dostaje wiadomość 'śpisz?' od osoby, która nie powinna pisać.","Na stole ląduje telefon z otwartą rozmową z tajemniczym serduszkiem.","Ktoś proponuje randkę w ciemno jednej osobie ze stada.","Były wrzuca zdjęcie z kimś nowym dokładnie podczas waszej imprezy.","Jedna owca twierdzi, że umie rozpoznać red flag po trzech zdaniach.","Na imprezie pojawia się ktoś absurdalnie atrakcyjny, ale bardzo dziwny.","Ktoś pyta, czy warto wrócić do ex po 'ostatnią rozmowę'.","Jedna owca dostaje dwa zaproszenia na randkę na ten sam wieczór.","Nieznajomy prosi stado o poradę przed pierwszą randką.","Jedna owca odkrywa, że jej crush ogląda wszystkie stories, ale nigdy nie pisze.","Ktoś proponuje wspólne przeglądanie profili randkowych.","Na randce ktoś mówi 'nie szukam niczego poważnego' po czym pyta o imiona dzieci.","Jedna owca ma wysłać pierwszą wiadomość do osoby, która jej się podoba.","Stado musi wybrać najgorszy tekst na podryw, który ma szansę zadziałać.","Ktoś z przeszłości lajkuje zdjęcie sprzed siedmiu lat.","Jedna owca dostaje kwiaty bez podpisu.","Na weselu zostaje jedno miejsce obok bardzo ciekawego singla.","Ktoś proponuje sprawdzić telefon partnera 'tylko dla spokoju'.","Jedna owca mówi, że zna sekret udanego związku po dwóch drinkach.","Na wakacjach poznajecie grupę ludzi, a jedna osoba natychmiast wpada komuś w oko.","Ktoś pyta, czy powiedzieć przyjaciółce, że jej partner flirtował.","Jedna owca przypadkiem wysyła wiadomość o kimś bezpośrednio do tej osoby.","Crush odpisuje po trzech dniach jednym emoji.","Jedna owca ma wybrać między chemią a rozsądkiem.","Ktoś proponuje romantyczny gest, który może być genialny albo przerażający.","Na randce pada pytanie o najbardziej wstydliwy sekret.","Jedna owca spotyka kogoś idealnego, kto ma jedną ogromną wadę.","Stado musi zdecydować, czy miłość usprawiedliwia naprawdę głupi pomysł."
    ],
    "Przyjaźń": [
      "Jedna owca nie została zaproszona na imprezę, na której są wszyscy inni.","Ktoś zdradza sekret i natychmiast mówi 'ale nikomu nie mów'.","Stado odkrywa, że dwie owce od miesięcy mają osobny czat.","Jedna osoba zawsze spóźnia się dokładnie 47 minut.","Ktoś pożyczył ulubioną rzecz i oddał ją w stanie wojennym.","Jedna owca zaczyna spotykać się z kimś, kogo reszta stada nie znosi.","Ktoś chce powiedzieć przyjaciółce brutalną prawdę o jej fryzurze.","Stado ma wybrać osobę, której powierzyłoby najbardziej kompromitujący sekret.","Jedna owca organizuje wyjazd i robi arkusz kalkulacyjny z harmonogramem.","Ktoś odwołuje wspólne plany pięć minut przed wyjściem.","Jedna owca zawsze mówi 'zaraz wracam' i znika na godzinę.","Ktoś potrzebuje alibi na bardzo głupią decyzję.","Stado musi wybrać, kto najlepiej poradziłby sobie z kryzysem o 3:00 rano.","Jedna owca zakochuje się w osobie, która wcześniej podobała się jej przyjaciółce.","Ktoś po raz piąty wraca do tej samej toksycznej historii.","Jedna owca twierdzi, że umie zachować każdy sekret.","Stado dostaje tylko dwa bilety na koncert marzeń.","Ktoś publikuje zdjęcie grupowe, na którym jedna owca wygląda fatalnie.","Jedna owca potrzebuje pomocy w przeprowadzce o 7 rano w sobotę.","Ktoś zaczyna randkować z byłym swojej znajomej.","Stado ma wspólnie kupić prezent, ale budżety są bardzo różne.","Jedna owca mówi coś zbyt szczerego przy niewłaściwej osobie.","Ktoś potrzebuje natychmiastowego wsparcia po katastrofalnej randce.","Jedna owca zawsze przejmuje kontrolę nad planem wieczoru.","Stado odkrywa, że jedna osoba zna plotkę o wszystkich.","Ktoś chce wrzucić do sieci filmik, na którym reszta stada zachowuje się fatalnie.","Jedna owca pyta, czy przyjaźń powinna przetrwać absolutnie wszystko.","Ktoś zapomniał o urodzinach najbliższej osoby.","Stado musi wskazać najbardziej lojalną owcę.","Jedna osoba proponuje zasadę: dziś żadnych tajemnic."
    ],
    "Wstyd": [
      "Telefon jednej owcy zaczyna głośno odtwarzać coś, czego zdecydowanie nie miał.","Ktoś potyka się przed osobą, na której bardzo chce zrobić wrażenie.","Jedna owca wysyła screenshot rozmowy do osoby z tego screenshota.","Stado spotyka nauczyciela z podstawówki podczas bardzo niepoważnej sytuacji.","Ktoś zapomina imienia osoby, z którą rozmawia od dwudziestu minut.","Jedna owca macha komuś, kto wcale nie machał do niej.","Ktoś wchodzi do złego samochodu i zaczyna zapinać pas.","Jedna owca odpowiada 'wzajemnie' na życzenia, na które nie da się tak odpowiedzieć.","Stado zostaje rozpoznane na zdjęciu z poprzedniej nocy.","Ktoś mówi coś złośliwego o osobie stojącej tuż za nim.","Jedna owca ma plamę na ubraniu i dowiaduje się jako ostatnia.","Ktoś myli partnera znajomej z jej bratem.","Jedna owca wpada do basenu w pełnym ubraniu.","Stado musi wybrać, kto najlepiej udaje, że nic się nie stało.","Ktoś zaczyna śpiewać tekst piosenki kompletnie niepoprawnie.","Jedna owca przypadkiem uruchamia filtr podczas ważnej rozmowy wideo.","Ktoś przesyła głosówkę do niewłaściwego czatu.","Jedna owca próbuje otworzyć drzwi, które trzeba pchnąć, przez stanowczo za długo.","Stado zostaje poproszone o wyjaśnienie dziwnego zdjęcia.","Ktoś myśli, że zna celebrytę i podchodzi się przywitać.","Jedna owca ma na telefonie alarm z bardzo kompromitującą nazwą.","Ktoś orientuje się, że od godziny ma metkę na wierzchu.","Jedna owca mówi 'kocham cię' przy kończeniu całkiem nieromantycznej rozmowy.","Stado słyszy własną rozmowę odtworzoną z głośnika.","Ktoś wita obcą osobę jak starego znajomego.","Jedna owca próbuje dyskretnie opuścić imprezę i przewraca stojak z kurtkami.","Ktoś przypadkiem reaguje serduszkiem na zdjęcie sprzed ośmiu lat.","Jedna owca zasypia w najmniej odpowiednim momencie.","Stado ma opowiedzieć historię, której nikt nie powinien nagrywać.","Ktoś odkrywa, że przez pół wieczoru miał włączony mikrofon."
    ],
    "Pieniądze": [
      "Rachunek za kolację jest absurdalnie wysoki i nikt nie pamięta, kto zamawiał ostrygi.","Jedna owca proponuje spontaniczny wyjazd, który kosztuje miesięczny czynsz.","Ktoś wygrywa sporą kwotę i ma pięć minut na decyzję, co z nią zrobić.","Stado znajduje portfel wypchany gotówką.","Jedna owca kupuje coś kompletnie niepotrzebnego, ale spektakularnego.","Ktoś proponuje wspólną inwestycję po trzech drinkach.","Jedna owca pożycza pieniądze i od miesięcy nie wspomina o oddaniu.","Stado ma wybrać najbardziej nieodpowiedzialny luksus.","Ktoś chce zapłacić fortunę za stolik VIP.","Jedna owca dostaje niespodziewaną premię.","Na aukcji pojawia się przedmiot, którego absolutnie nie potrzebujecie.","Ktoś twierdzi, że ma pewny sposób na szybkie wzbogacenie się.","Stado musi zdecydować, czy oszczędzić, czy zrobić historię na całe życie.","Jedna owca przypadkiem płaci za całą grupę.","Ktoś znajduje świetną ofertę wakacji, ale trzeba zapłacić natychmiast.","Jedna owca kupuje prezent dużo droższy niż ustalony limit.","Stado dostaje kupon na jeden absurdalny luksus.","Ktoś proponuje założyć wspólny biznes o północy.","Jedna owca ma wybrać: wygoda teraz czy dużo pieniędzy później.","Stado musi ustalić, kto najlepiej negocjuje cenę.","Ktoś chce kupić rzecz tylko dlatego, że jest limitowana.","Jedna owca twierdzi, że 'pieniądze są po to, żeby je wydawać'.","Stado ma jeden darmowy upgrade i musi zdecydować, kto go dostaje.","Ktoś proponuje bardzo drogie doświadczenie, które trwa 20 minut.","Jedna owca odkrywa błąd na rachunku na swoją korzyść.","Stado ma podzielić koszt prezentu między osoby o różnych budżetach.","Ktoś proponuje zakład za prawdziwe pieniądze.","Jedna owca kupuje coś pod wpływem reklamy o 2:00 w nocy.","Stado otrzymuje tajemniczą ofertę 'zbyt dobrą, by była prawdziwa'.","Ktoś mówi, że najlepsze wspomnienia zawsze są drogie."
    ],
    "Praca": [
      "Szef przypadkiem trafia na imprezę stada.","Jedna owca wysyła mema na oficjalny kanał firmowy.","Ktoś ma prezentację rano po zdecydowanie zbyt długim wieczorze.","Stado musi wskazać osobę, która najlepiej wybrnie z trudnego spotkania.","Jedna owca dostaje ofertę pracy marzeń w innym kraju.","Ktoś przypadkiem odpowiada wszystkim w firmowej korespondencji.","Jedna owca chce powiedzieć szefowi dokładnie, co myśli.","Stado ma wybrać osobę do negocjowania podwyżki.","Ktoś proponuje udawać awarię internetu podczas nudnego calla.","Jedna owca zostaje przyłapana na robieniu zakupów podczas spotkania online.","Firma organizuje absurdalny team building.","Ktoś ma pomysł na biznes, który brzmi głupio, ale może zadziałać.","Jedna owca zostaje przez pomyłkę zaproszona na spotkanie zarządu.","Stado musi wybrać, kto najszybciej zrobiłby karierę w korporacji.","Ktoś dostaje maila 'możemy porozmawiać?' bez żadnego kontekstu.","Jedna owca ma możliwość przejęcia projektu po niepopularnym koledze.","Stado może wprowadzić jedną nową zasadę w pracy.","Ktoś zasypia na kamerze podczas wideokonferencji.","Jedna owca odkrywa, że współpracownik przypisuje sobie jej pomysł.","Stado musi zdecydować, czy powiedzieć prawdę klientowi, czy kupić czas.","Ktoś chce rzucić pracę bez planu B.","Jedna owca może dostać awans kosztem dużo większej odpowiedzialności.","Stado musi wybrać, kto najlepiej udaje profesjonalizm w chaosie.","Ktoś przypadkiem ma włączoną kamerę w nieodpowiednim momencie.","Jedna owca ma pięć minut na przygotowanie przemówienia dla 300 osób.","Stado odkrywa, że firmowy wyjazd ma tylko jeden pokój premium.","Ktoś chce zabrać psa na bardzo oficjalne spotkanie.","Jedna owca otrzymuje wiadomość od rekrutera konkurencji.","Stado ma wybrać najgorszy możliwy tekst do automatycznej odpowiedzi mailowej.","Ktoś proponuje 'krótkie spotkanie', które już trwa dwie godziny."
    ],
    "Wakacje": [
      "Stado spóźniło się na samolot o siedem minut.","Hotel twierdzi, że wasza rezerwacja jest na przyszły miesiąc.","Jedna owca chce wynająć skuter mimo że nigdy na nim nie jeździła.","Na plaży znika torba z najważniejszymi rzeczami.","Stado może pojechać na tajemniczą wycieczkę bez opinii w internecie.","Jedna owca chce zostać na wakacjach o trzy dni dłużej.","W hotelu zostało tylko jedno łóżko z najlepszym widokiem.","Ktoś proponuje spontaniczne nurkowanie o wschodzie słońca.","Stado zgubiło drogę w miejscu bez zasięgu.","Jedna owca zaprzyjaźnia się z lokalną ekipą i proponuje zmianę planów.","Wasz lot jest opóźniony o dziewięć godzin.","Ktoś chce spróbować potrawy, której nazwy nikt nie potrafi wymówić.","Stado ma wybrać osobę odpowiedzialną za wspólny paszportowy chaos.","Jedna owca wraca do hotelu z ogromnym dmuchanym flamingiem.","Ktoś proponuje nocleg w miejscu wyglądającym świetnie tylko na jednym zdjęciu.","Stado może dostać darmowy lot, ale kierunek pozna dopiero na lotnisku.","Jedna owca chce wstać o 4:30 na wschód słońca.","Ktoś znajduje ukrytą plażę za znakiem 'zakaz wstępu'.","Stado ma jeden dzień i zbyt wiele atrakcji.","Jedna owca kupuje lokalny strój i chce w nim chodzić cały dzień.","Ktoś proponuje przejażdżkę łodzią podczas podejrzanej pogody.","Stado musi zdecydować, czy zgłosić zgubiony telefon, czy iść dalej na imprezę.","Jedna owca zna trzy słowa w lokalnym języku i przejmuje negocjacje.","Ktoś chce zrobić tatuaż jako pamiątkę z wyjazdu.","Stado dostaje możliwość darmowej zamiany hotelu na coś kompletnie nieprzewidywalnego.","Jedna owca chce wrócić z wakacji bez żadnych zdjęć.","Ktoś proponuje wyjazd bez planu i bez rezerwacji.","Stado odkrywa, że lokalny festiwal zaczyna się za godzinę.","Jedna owca chce przywieźć do domu bardzo dziwną pamiątkę.","Ostatniego dnia wakacji macie czas tylko na jedną rzecz."
    ],
    "Moralne katastrofy": [
      "Kasjer wydaje wam o 100 zł za dużo.","Jedna owca zna kompromitujący sekret osoby, która właśnie ją obraziła.","Stado może ominąć ogromną kolejkę dzięki bardzo małemu kłamstwu.","Ktoś znajduje telefon bez blokady i z otwartymi wiadomościami.","Jedna owca może wygrać zakład, jeśli przemilczy ważny szczegół.","Stado wie, że znajoma popełnia ogromny błąd, ale nie pyta o radę.","Ktoś prosi was o alibi w sprawie, która jest głupia, ale nieszkodliwa.","Jedna owca słyszy plotkę, która jest zbyt dobra, żeby jej nie powtórzyć.","Stado ma okazję zabrać ostatni stolik komuś, kto odszedł na minutę.","Ktoś zostawia bardzo drogi przedmiot bez opieki.","Jedna owca może ujawnić prawdę, która zepsuje idealny wieczór.","Stado dostaje informację przeznaczoną zdecydowanie nie dla niego.","Ktoś prosi o szczerą opinię, ale wygląda na osobę niegotową na szczerość.","Jedna owca może uratować siebie, zrzucając winę na anonimową osobę.","Stado odkrywa, kto naprawdę zjadł ostatni kawałek tortu.","Ktoś chce wykorzystać cudzą rezerwację, bo nazwisko się zgadza.","Jedna owca może podejrzeć wynik konkursu przed ogłoszeniem.","Stado musi wybrać między lojalnością a powiedzeniem prawdy.","Ktoś prosi, żeby nic nie mówić o sytuacji, która wygląda podejrzanie.","Jedna owca przypadkiem poznaje cudzy PIN.","Stado może dostać darmowy upgrade, jeśli nie sprostuje pomyłki obsługi.","Ktoś chce przeczytać wiadomość widoczną na cudzym ekranie.","Jedna owca ma możliwość zemsty bez ryzyka wykrycia.","Stado zna odpowiedź w konkursie dzięki przypadkowo usłyszanej rozmowie.","Ktoś prosi o ocenę, czy drobne kłamstwo dla świętego spokoju jest OK.","Jedna owca może uniknąć mandatu, udając kompletną niewiedzę.","Stado znajduje bardzo wartościowy przedmiot bez oznaczeń właściciela.","Ktoś chce ukryć wpadkę, zanim ktokolwiek ją zauważy.","Jedna owca może powiedzieć komuś prawdę, która niczego nie naprawi.","Stado musi zdecydować: zasady czy dobra historia."
    ],
    "Absurd": [
      "Kosmici lądują i proszą o wybranie ambasadora stada.","Jedna owca budzi się i odkrywa, że potrafi czytać myśli przez godzinę.","Stado dostaje milion złotych, ale musi wydać je do północy.","Wilk proponuje wam rozejm i wspólny biznes.","Jedna owca zostaje przez pomyłkę królową małego państwa.","Stado trafia do teleturnieju, którego zasad nikt nie rozumie.","Ktoś znajduje przycisk z napisem 'NIE NACISKAĆ'.","Jedna owca może zamienić się życiem z celebrytą na tydzień.","Stado musi wybrać supermoc, która ma absurdalny efekt uboczny.","Przed wami pojawia się wehikuł czasu z jednym wolnym miejscem.","Jedna owca może przez dzień mówić wyłącznie prawdę.","Stado zostaje zamknięte w centrum handlowym na całą noc.","Ktoś oferuje wam mapę prowadzącą do 'prawie na pewno' skarbu.","Jedna owca zostaje niewidzialna do rana.","Stado może wprowadzić jedno nowe prawo obowiązujące wszystkich ludzi.","Ktoś proponuje adopcję małej żyrafy jako maskotki grupy.","Jedna owca może usunąć jedno słowo ze wszystkich języków świata.","Stado ma przeżyć tydzień bez telefonów za bardzo dużą nagrodę.","Ktoś daje wam pilot pozwalający zatrzymać czas na 60 sekund.","Jedna owca może poznać jedną odpowiedź dotyczącą swojej przyszłości.","Stado trafia na bezludną wyspę z jednym kompletnie niepraktycznym przedmiotem.","Ktoś oferuje wam możliwość cofnięcia jednej imprezowej decyzji.","Jedna owca zostaje prowadzącą własnego reality show.","Stado może zamienić jedną osobę w owcę na 24 godziny.","Ktoś twierdzi, że jutro koniec świata i ma bardzo przekonujący wykres.","Jedna owca może przez godzinę słyszeć, co ludzie naprawdę o niej myślą.","Stado otrzymuje zaproszenie na wesele na Księżycu.","Ktoś oferuje wam jeden dzień absolutnego szczęścia bez wspomnień z niego.","Jedna owca może dostać dowolną rzecz, ale wybiera ją reszta grupy.","Stado ma pięć minut na wybranie nowej oficjalnej religii owiec."
    ],
    "Charakter": [
      "Stado musi wybrać osobę, która najlepiej zachowuje zimną krew.","Jedna owca ma podjąć decyzję za wszystkich bez konsultacji.","Ktoś krytykuje waszą grupę i trzeba zdecydować, jak reagować.","Stado ma wskazać osobę, która najłatwiej zaprzyjaźnia się z obcymi.","Jedna owca musi poprowadzić grupę przez kompletny chaos.","Ktoś pyta, kto z was najlepiej umie powiedzieć 'nie'.","Stado ma wybrać osobę, która najczęściej robi coś wbrew opinii innych.","Jedna owca musi zdecydować między spokojem a przygodą.","Ktoś pyta, kto najlepiej rozładowuje napięcie żartem.","Stado musi wskazać osobę najbardziej podatną na spontaniczne pomysły.","Jedna owca ma przyznać się do błędu przed całą grupą.","Ktoś pyta, kto najdłużej pamięta urazę.","Stado musi wybrać osobę, która najlepiej negocjuje kompromis.","Jedna owca może przejąć kontrolę albo pozwolić zdecydować innym.","Ktoś pyta, kto najczęściej zmienia zdanie po dobrej argumentacji.","Stado ma wskazać największego ryzykanta.","Jedna owca musi wybrać między wygodą a ciekawością.","Ktoś pyta, kto najczęściej mówi to, co inni tylko myślą.","Stado musi wskazać osobę, która najłatwiej wybacza.","Jedna owca dostaje szansę na coś ekscytującego, ale niepewnego.","Ktoś pyta, kto najczęściej przejmuje odpowiedzialność, gdy robi się źle.","Stado ma wskazać osobę najbardziej skłonną do improwizacji.","Jedna owca może uratować plan, łamiąc wcześniej ustalone zasady.","Ktoś pyta, kto najlepiej wyczuwa ludzi.","Stado musi wybrać osobę, która najczęściej idzie własną drogą.","Jedna owca musi zdecydować, czy powiedzieć coś niewygodnego.","Ktoś pyta, kto najczęściej działa najpierw, a myśli potem.","Stado ma wskazać osobę, która najlepiej zachowuje tajemnice.","Jedna owca musi wybrać między byciem lubianą a postawieniem na swoim.","Ktoś pyta, kto z was byłby najlepszym przywódcą stada."
    ]
  };

  const answerSets = [
    ["Robimy to rozsądnie i bez dramatu.","Idziemy za energią grupy i zobaczymy, co się stanie.","Wybieramy opcję, której nikt się po nas nie spodziewa.","Najpierw pytamy najbardziej podejrzaną owcę.","Robimy z tego historię, którą będziemy opowiadać latami."],
    ["Mówimy prawdę, nawet jeśli zaboli.","Chronimy swoje stado za wszelką cenę.","Udawajmy, że niczego nie widzieliśmy.","Podejmujemy ryzyko - raz się żyje.","Zrzucamy decyzję na losowanie."],
    ["Najpierw zbieramy fakty.","Słuchamy najbardziej doświadczonej owcy.","Robimy dokładnie odwrotnie niż podpowiada rozsądek.","Wybieramy najzabawniejszą opcję.","Każda owca ratuje się sama."],
    ["Grzecznie odpuszczamy.","Negocjujemy do skutku.","Robimy scenę godną reality show.","Wysyłamy Czarną Owcę na pierwszy ogień.","Podejmujemy szybką decyzję bez analizowania."],
    ["Wybieramy bezpieczeństwo.","Wybieramy najlepszą historię.","Wybieramy to, co zrobiłaby większość ludzi.","Wybieramy najbardziej kontrowersyjną możliwość.","Oddajemy decyzję osobie z najmniejszą liczbą punktów."],
    ["Mówimy: absolutnie nie.","Mówimy: czemu nie?","Najpierw robimy zdjęcie na pamiątkę.","Pytamy obcą osobę o opinię.","Robimy plan B, C i D naraz."],
    ["Ratujemy reputację.","Ratujemy wieczór.","Ratujemy pieniądze.","Ratujemy przyjaźń.","Nie ratujemy niczego - chcemy zobaczyć chaos."],
    ["Wybieramy najmniejsze ryzyko.","Wybieramy największą nagrodę.","Wybieramy coś, co da najlepszą plotkę.","Wybieramy coś, co za tydzień będzie śmieszne.","Wybieramy coś, czego jutro prawdopodobnie pożałujemy."],
    ["Działamy natychmiast.","Czekamy pięć minut i obserwujemy.","Przerzucamy odpowiedzialność na Barana.","Robimy demokratyczne głosowanie nad głosowaniem.","Każemy najodważniejszej owcy zdecydować."],
    ["Zachowujemy klasę.","Zachowujemy tylko dowody.","Zachowujemy się, jakby to był nasz plan od początku.","Robimy z tego konkurs.","Uciekamy, zanim pojawią się konsekwencje."]
  ];

  const traitsForAnswer = [
    {conformism:3, empathy:2, risk:0, chaos:0, dominance:0, honesty:2, hedonism:0, pragmatism:3, romance:0, independence:0},
    {conformism:2, empathy:1, risk:2, chaos:2, dominance:1, honesty:0, hedonism:2, pragmatism:0, romance:1, independence:1},
    {conformism:0, empathy:0, risk:3, chaos:3, dominance:2, honesty:1, hedonism:2, pragmatism:0, romance:0, independence:3},
    {conformism:1, empathy:1, risk:1, chaos:1, dominance:3, honesty:1, hedonism:0, pragmatism:2, romance:0, independence:2},
    {conformism:0, empathy:1, risk:2, chaos:2, dominance:0, honesty:0, hedonism:3, pragmatism:0, romance:2, independence:2}
  ];

  const qs = [];
  let id = 1;
  Object.entries(categories).forEach(([category, scenarios], ci) => {
    scenarios.forEach((scenario, i) => {
      const set = answerSets[(i + ci * 3) % answerSets.length];
      qs.push({
        id: id++, category, intensity: 1 + ((i + ci) % 3),
        scene: ["club","beach","city","party","space","office"][(i+ci)%6],
        question: scenario + " Co robi stado?",
        answers: set.map((text, ai) => ({text, traits: {...traitsForAnswer[ai]}}))
      });
    });
  });
  window.STADO_QUESTIONS = qs.slice(0,300);

  window.STADO_NICKNAMES = [
    "Owca Podejrzanych Decyzji","Owca Po Trzecim Prosecco","Owca Bez Filtra","Owca Korporacyjna","Owca Romantyczna Katastrofa","Owca Niewinnego Spojrzenia","Owca Podwyższonego Ryzyka","Owca Złej Rady","Owca Cudzych Problemów","Owca Jednej Nocy","Owca Premium","Owca Po Godzinach","Owca Kontrolowanego Chaosu","Owca Nieczytająca Regulaminów","Owca Wiecznego Afteru","Owca Dobrej Wymówki","Owca Ostatniego Słowa","Owca Dramy Umiarkowanej","Owca Dzikiego Pomysłu","Owca Zbyt Szczera","Owca Wielkiego Wyjścia","Owca Różowych Okularów","Owca Bez Planu B","Owca Przypadkowej Mądrości","Owca Strategicznego Flirtu","Owca Przedłużonego Weekendu","Owca Podejrzanej Pewności Siebie","Owca Wysokich Standardów","Owca Niskiego Hamulca","Owca Złotych Myśli","Owca Trudnych Pytań","Owca Łatwych Odpowiedzi","Owca Nocnej Zmiany","Owca Jednego Drinka","Owca Dwóch Telefonów","Owca Bardzo Ważnych Spraw","Owca Niepotrzebnych Zakupów","Owca Dobrej Historii","Owca Niebezpiecznej Ciekawości","Owca Świętego Spokoju","Owca Wielkich Emocji","Owca Cichego Sabotażu","Owca Czystego Przypadku","Owca Bez Dowodów","Owca Tajnego Planu","Owca Wiecznej Racjonalizacji","Owca Mocnego Wejścia","Owca Miękkiego Lądowania","Owca Szybkiej Decyzji","Owca Drugiej Szansy"
  ];
})();
